# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_SKY)	+= switch_sky.o

obj-$(CONFIG_EF33_BOARD)	+= pansw_class.o
obj-$(CONFIG_EF34_BOARD)	+= pansw_class.o
obj-$(CONFIG_EF35_BOARD)	+= pansw_class.o

